#!/usr/bin/env bash

set -o nounset
set -o errexit



case "$1" in
	#
	# ========= Main Docker infrastructure =========
	# 
	ngx-proxy)
	    docker run -it -p 80:80 --restart unless-stopped \
			--name ngx-proxy \
			-v /var/run/docker.sock:/tmp/docker.sock:ro \
			jwilder/nginx-proxy
		;;
	dokku)
		docker run -it -p 3022:22 -p 3020:80 -p 3021:443 --name dokku \
		    -e DOKKU_HOSTNAME=dokku.vm  \
			-e VIRTUAL_HOST="*.dokku.vm,dokku.vm,*.dokku" -e VIRTUAL_PORT=80 \
			-v ~/Local/docker-data/dokku:/mnt/dokku \
			-v /var/run/docker.sock:/var/run/docker.sock \
			dokku/dokku:0.21.4
		;;
	#
	# ========= Search engines =========
	# 
	osearch)
	    docker run -it -p 9013:9090 \
			-e VIRTUAL_HOST=osearch.\* --name osearch \
			-v ~/Local/docker-data/opensearchserver:/srv \
			alexandretoyer/opensearchserver
		;;
	searx)
		docker run -it -p 9010:8080 \
			-e VIRTUAL_HOST=searx.\* --name searx \
			-v ~/Local/docker-data/searx:/etc/searx \
			searx/searx
		;;
	yacy)
		docker run -it -p 9011:9011 -p 9012:9012 -e VIRTUAL_PORT=9011 \
			-e VIRTUAL_HOST="yacy.*"  --name yacy \
			--log-opt max-size=200m --log-opt max-file=2 \
			-v yacy:/opt/yacy_search_server/DATA \
			yacy/yacy_search_server
		;;
	# yacy-pvt)
	# 	docker run -it --name yacy-pvt -p 9014:8090 -p 9015:8443 \
	# 	  -v ~/Local/docker-data/yacy-pvt:/opt/yacy_search_server/DATA \
	# 	  -e VIRTUAL_HOST="yacy-pvt.*"  -e VIRTUAL_PORT=8090 \
	# 	  --log-opt max-size=200m --log-opt max-file=2 \
	# 	  yacy/yacy_search_server
	# 	;;
	#
	# ========= Agent automation =========
	# 
	huginn)
		docker run -it -p 9100:3000 \
			-e VIRTUAL_HOST="huginn.*" --name huginn \
			huginn/huginn
		;;
	n8n)
		docker run -it -p 9101:5678 \
			-e VIRTUAL_HOST="n8n.*" --name n8n \
			-v n8n:/root/.n8n \
			n8nio/n8n
		;;
	#
	# ========= Bookmark managers =========
	# 
	bukuserver)
		docker run -it -p 9023:5001 \
			-e VIRTUAL_HOST=buku.\* --name bukuserver \
			-v ~/.local/share/buku:/root/.local/share/buku \
			bukuserver
		;;
	linkding)
	    docker run -it -p 9020:9090 \
			-e VIRTUAL_HOST="linkding.*"  --name linkding \
			-v ~/Local/docker-data/linkding:/etc/linkding/data \
			sissbruecker/linkding:latest
		;;
	golinks)
	    docker run -d -p 9021:8000 \
		-e VIRTUAL_HOST=golinks.\* --name golinks \
		prologic/golinks
		;;
	shaarli)
		docker run -it -p 9022:80 \
			-e VIRTUAL_HOST="shaarli.*" --name shaarli \
			-v ~/Local/docker-data/shaarli-data:/var/www/shaarli/data \
			-v shaarli-cache:/var/www/shaarli/cache \
			shaarli/shaarli:latest
		;;
	#
	# ========= Other stuff =========
	# 
	#
	# rover)
	# 	# For localuse need to add:
	# 	#     -e MAIN_NODE_IP_ADDRESS='127.0.0.1'
	# 	# or
	# 	# 		 -e BY_PASS_PROXY_CHECK='TRUE'
	# 	docker run -d -p 3180:80 -p 3143:443 -p 3100:3000 --name rover \
	# 		-e MAIN_NODE_IP_ADDRESS='127.0.0.1' \
	# 		-e VIRTUAL_HOST="*.rover.vm,rover.vm,*.rover" -e VIRTUAL_PORT=80 \
	# 		-v /var/run/docker.sock:/var/run/docker.sock \
	# 		-v captain:/captain caprover/caprover
	# 	;;
	*)
		# echo $"Usage: $0 {image name} {container name}"
		echo $"Usage: $0 <image name>"
		exit 1

esac

