#! /bin/sh

# # first strip frontmatter
# gsed '1 { /^---/ { :a N; /\n---/! ba; d} }
# 		# then strip comments
# 		s/[[:space:]]*#.*$//
# 		# then strip leading spaces, trailing spaces and empty lines
# 		s/[[:space:]]//g  ;  /^$/d' "$1"
		

# first strip comments
sed 's/#.*$//
	# then strip leading spaces, trailing spaces and empty lines
	s/[[:space:]]//g
	/^$/d' "$1"